version: '3.8'

services:
  oracle-db:
    image: your-dockerhub-username/my-oracle-db:latest  # O el nombre que le diste a tu imagen personalizada
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=tu_contraseña_segura  # Contraseña para el usuario sys
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "db_tech_emporium/tu_contraseña@//localhost:1521/XE", "AS", "SYSDBA", "AND", "EXIT"]
      interval: 30s
      timeout: 10s
      retries: 5

  spring-app:
    build: .  # Asume que tienes un Dockerfile para tu aplicación Spring Boot en el mismo directorio
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/XE
      - SPRING_DATASOURCE_USERNAME=db_tech_emporium
      - SPRING_DATASOURCE_PASSWORD=tu_contraseña
    depends_on:
      oracle-db:
        condition: service_healthy

volumes:
  oracle-data: