ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER c##db_tech_emporium IDENTIFIED BY enrique;
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
ALTER SYSTEM SET "_COMMON_USER_PREFIX"='';

CREATE USER db_tech_emporium IDENTIFIED BY enrique;

GRANT CONNECT, RESOURCE TO db_tech_emporium;
GRANT CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER TO db_tech_emporium;
GRANT UNLIMITED TABLESPACE TO db_tech_emporium;

ALTER SESSION SET CURRENT_SCHEMA = db_tech_emporium;